// Copyright (c) 2010 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// -------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool and should not edited
// by hand. See the translator.README.txt file in the tools directory for
// more information.
//

#ifndef _BROWSER_CTOCPP_H
#define _BROWSER_CTOCPP_H

#ifndef USING_CEF2_SHARED
#pragma message("Warning: "__FILE__" may be accessed wrapper-side only")
#else // USING_CEF2_SHARED

#include "include/cef2.h"
#include "include/cef2_capi.h"
#include "libcef_dll/ctocpp/ctocpp.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class CefBrowserCToCpp
    : public CefCToCpp<CefBrowserCToCpp, CefBrowser, cef_browser_t>
{
public:
  CefBrowserCToCpp(cef_browser_t* str)
      : CefCToCpp<CefBrowserCToCpp, CefBrowser, cef_browser_t>(str) {}
  virtual ~CefBrowserCToCpp() {}

  // CefBrowser methods
  virtual CefRefPtr<CefProfile> GetProfile();
  virtual void Destroy();
  virtual std::wstring GetIdString();
  virtual CefWindowHandle GetWindowHandle();
  virtual CefRefPtr<CefTab> CreateTab(int index, const std::wstring& url,
      const std::wstring& referrer, bool foreground);
  virtual int GetTabCount();
  virtual CefRefPtr<CefTab> GetTab(int index);
  virtual CefRefPtr<CefTab> GetSelectedTab();
};

#endif // USING_CEF_SHARED
#endif // _BROWSER_CTOCPP_H

