// Copyright (c) 2010 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// A portion of this file was generated by the CEF translator tool.  When
// making changes by hand only do so within the body of existing static and
// virtual method implementations. See the translator.README.txt file in the
// tools directory for more information.
//

#include "libcef_dll/cpptoc/browser_cpptoc.h"
#include "libcef_dll/ctocpp/browser_listener_ctocpp.h"


// VIRTUAL METHODS - Body may be edited by hand.

void CefBrowserListenerCToCpp::OnCreate(CefRefPtr<CefBrowser> browser)
{
  if(CEF_MEMBER_MISSING(struct_, on_create))
    return;

  struct_->on_create(struct_, CefBrowserCppToC::Wrap(browser));
}

void CefBrowserListenerCToCpp::OnDestroy(CefRefPtr<CefBrowser> browser)
{
  if(CEF_MEMBER_MISSING(struct_, on_destroy))
    return;

  struct_->on_destroy(struct_, CefBrowserCppToC::Wrap(browser));
}


#ifdef _DEBUG
long CefCToCpp<CefBrowserListenerCToCpp, CefBrowserListener,
    cef_browser_listener_t>::DebugObjCt = 0;
#endif

