// Copyright (c) 2010 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// -------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool and should not edited
// by hand. See the translator.README.txt file in the tools directory for
// more information.
//

#ifndef _BROWSERLISTENER_CTOCPP_H
#define _BROWSERLISTENER_CTOCPP_H

#ifndef BUILDING_CEF2_SHARED
#pragma message("Warning: "__FILE__" may be accessed DLL-side only")
#else // BUILDING_CEF2_SHARED

#include "include/cef2.h"
#include "include/cef2_capi.h"
#include "libcef_dll/ctocpp/ctocpp.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed DLL-side only.
class CefBrowserListenerCToCpp
    : public CefCToCpp<CefBrowserListenerCToCpp, CefBrowserListener,
        cef_browser_listener_t>
{
public:
  CefBrowserListenerCToCpp(cef_browser_listener_t* str)
      : CefCToCpp<CefBrowserListenerCToCpp, CefBrowserListener,
          cef_browser_listener_t>(str) {}
  virtual ~CefBrowserListenerCToCpp() {}

  // CefBrowserListener methods
  virtual void OnCreate(CefRefPtr<CefBrowser> browser);
  virtual void OnDestroy(CefRefPtr<CefBrowser> browser);
};

#endif // BUILDING_CEF_SHARED
#endif // _BROWSERLISTENER_CTOCPP_H

