// Copyright (c) 2010 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// -------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool and should not edited
// by hand. See the translator.README.txt file in the tools directory for
// more information.
//

#ifndef _TABLISTENER_CTOCPP_H
#define _TABLISTENER_CTOCPP_H

#ifndef BUILDING_CEF2_SHARED
#pragma message("Warning: "__FILE__" may be accessed DLL-side only")
#else // BUILDING_CEF2_SHARED

#include "include/cef2.h"
#include "include/cef2_capi.h"
#include "libcef_dll/ctocpp/ctocpp.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed DLL-side only.
class CefTabListenerCToCpp
    : public CefCToCpp<CefTabListenerCToCpp, CefTabListener, cef_tab_listener_t>
{
public:
  CefTabListenerCToCpp(cef_tab_listener_t* str)
      : CefCToCpp<CefTabListenerCToCpp, CefTabListener, cef_tab_listener_t>(
          str) {}
  virtual ~CefTabListenerCToCpp() {}

  // CefTabListener methods
  virtual void OnCreate(CefRefPtr<CefTab> tab);
  virtual void OnDestroy(CefRefPtr<CefTab> tab);
  virtual void OnAddressChange(CefRefPtr<CefTab> tab, const std::wstring& url);
  virtual void OnTitleChange(CefRefPtr<CefTab> tab, const std::wstring& title);
  virtual void OnNavStateChange(CefRefPtr<CefTab> tab, bool can_go_back,
      bool can_go_forward);
  virtual void OnSelectChange(CefRefPtr<CefTab> tab, bool selected);
  virtual void OnLoadStart(CefRefPtr<CefTab> tab);
  virtual void OnLoadStop(CefRefPtr<CefTab> tab);
};

#endif // BUILDING_CEF_SHARED
#endif // _TABLISTENER_CTOCPP_H

