// Copyright (c) 2010 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool and should not edited
// by hand. See the translator.README.txt file in the tools directory for
// more information.
//
#ifndef _PROFILE_CPPTOC_H
#define _PROFILE_CPPTOC_H

#ifndef BUILDING_CEF2_SHARED
#pragma message("Warning: "__FILE__" may be accessed DLL-side only")
#else // BUILDING_CEF2_SHARED

#include "include/cef2.h"
#include "include/cef2_capi.h"
#include "libcef_dll/cpptoc/cpptoc.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed DLL-side only.
class CefProfileCppToC
    : public CefCppToC<CefProfileCppToC, CefProfile, cef_profile_t>
{
public:
  CefProfileCppToC(CefProfile* cls);
  virtual ~CefProfileCppToC() {}
};

#endif // BUILDING_CEF_SHARED
#endif // _PROFILE_CPPTOC_H

